[package]
name = "recho"
about = "Echo clone built in Rust"
author = "C. Kusabs <dev.kusabs@gmail.com>"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"

